### ISSUE TITLE
When a dataset with IRI is imported, LODC catalog mode should be chosen

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#177]
Now, when I download a dataset for LODC and import it from file, the publisher and dataset IRIs are imported, however, the NODC mode is selected instead of LODC. In this case it should be LODC.

We should create a map of possible entry points (dataset in URL, dataset POSTes, dataset from file, dataset from URL, no input dataset) and expected behavior for various combinations of missing or present dataset and publisher IRIs.

**Comment by skodapetr** [comment]
Well datasets from NODC also have IRI , so that would mean that you get also export LODC for NODC datasets.  As a result, dataset IRI should not be the decisive factor. 

## Import

As of now there are multiple entry points into the dialog:
 * default - empty dialog and export to NODC
 * with ```url``` - ```importFromUrl``` 
 * with ```dataset``` - ```importFromDataset```
 * with server data - ```importFromPostData```
 * with ```kopie``` - this one is used by the ```importFromDataset```.

The ```importFromUrl``` imports dataset from given IRI and set export to EXPORT_NKOD mode.

The ```importFromDataset```  import dataset from given IRI (apply a proxy setting from configuration). If the ```kopie``` is set then set EXPORT_NKOD export mode, else set export EXPORT_EDIT mode.

The ```importFromPostData``` import dataset from server prodided data and set export to EXPORT_LKOD.

## Export
Based on the export mode, the dataset/distributions/services IRIs are set upon export.
The ```EXPORT_NKOD``` set IRIs to empty (blank nodes). 
The  ```EXPORT_EDIT``` and ```EXPORT_LKOD``` basically preserve the IRI. But the IRI can be set from the UI, then it should overload the IRI provided upon the import.


As it is getting more and more complex I believe we shoul have a place (wiki?) where @jakubklimek specify requirments on the inputs and I provide implementation.

**Comment by skodapetr** [comment]
And also this is just the start of the application, we also need to know what should happen if user import the data using buttons ```load from file``` or ```load from url```.

**Comment by jakubklimek** [comment]
Provisionally in [Google Doc](https://docs.google.com/document/d/1D_4sFIs0j3Tv6Dk4HOMVdN5DMbxJBxnDTJNeCU4tlXI)

**Comment by jakubklimek** [comment]
After thinking it through, I suggest the following URL params:

- `dataset`/`datová-sada` with dataset IRI - Gets dataset via SPARQL, sets NKOD edit mode
- `copy-from-dataset`/`kopírovat-z-datové-sady` with dataset IRI - Gets dataset via SPARQL, sets NKOD create mode
- `file`/`soubor` with file IRI - Gets file with metadata, sets NKOD create mode

**Comment by jakubklimek** [comment]
URL params working as expected. Loading file does not - it still does not switch to LKOD create mode when loading e.g. https://github.com/opendata-mvcr/lkod-mvcr/blob/master/rpp/agendy.jsonld via button.

I am thinking we could add an additional type to the file downloaded in LKOD mode and search for this type in the imported files and determine NKOD/LKOD according to the presence of this additional type. E.g.:
```jsonld
"typ": ["Datová sada", "Datová sada lokálního katalogu"],
```
